"""new migration

Revision ID: 937703b2b9b7
Revises: 
Create Date: 2025-03-02 20:36:19.480600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937703b2b9b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_uuid'),
    schema='media_files'
    )
    op.create_index(op.f('ix_media_files_media_files_id'), 'media_files', ['id'], unique=False, schema='media_files')
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_type'),
    schema='static_content'
    )
    op.create_table('header_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('link_to', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['static_content.header_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='static_content'
    )
    op.create_index(op.f('ix_static_content_header_links_id'), 'header_links', ['id'], unique=False, schema='static_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_static_content_header_links_id'), table_name='header_links', schema='static_content')
    op.drop_table('header_links', schema='static_content')
    op.drop_table('components', schema='static_content')
    op.drop_index(op.f('ix_media_files_media_files_id'), table_name='media_files', schema='media_files')
    op.drop_table('media_files', schema='media_files')
    # ### end Alembic commands ###
